server:
  port: 8888

eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuezu1026/wyz-crm-config
          username: yuezu1026       # git仓库的账号
          password: yue123456      # git仓库的密码
 
  rabbitmq:
    host: localhost    
    port: 5672
    username: guest
    password: guest
