server:
  port: 9008

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

spring:  
  rabbitmq:
    host: rb2mq.wangyz.club     
    port: 5672
    username: yuezu1026
    password: wang123456